# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/afyonltecan/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/afyonltecan

#SENSORS
PRODUCT_COPY_FILES += \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libacdapi_clb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdapi_clb.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/hw/sensors.msm8226.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.vendor.msm8226.so \
    vendor/samsung/afyonltecan/proprietary/etc/alps_param.dat:$(TARGET_COPY_OUT_VENDOR)/etc/alps_param.dat \
    vendor/samsung/afyonltecan/proprietary/etc/alp_cal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/alp_cal.dat

#CAMERA
PRODUCT_COPY_FILES += \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/hw/camera.msm8226.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.legacy.msm8226.so \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/samsung/afyonltecan/proprietary/etc/E08QL_s5k4h5yb_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/E08QL_s5k4h5yb_module_info.xml \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common_res0.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common_res1.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_common.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_default_video.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_liveshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_panorama.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_preview.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_snapshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_video_hd.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_zslshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libchromatix_s5k4h5yb_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/E08QL_libchromatix_s5k4h5yb_zsl.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_common_res0.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_common.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_default_video.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_liveshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_panorama.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_preview.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_snapshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_imx219_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_zslshot.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libactuator_dw9804k_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804k_camcorder.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libactuator_dw9804k_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804k_camera.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_imx219.so:system/vendor/lib/libmmcamera_imx219.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so:system/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_s5k4ecgx.so:system/vendor/lib/libmmcamera_s5k4ecgx.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_s5k4h5yb.so:system/vendor/lib/libmmcamera_s5k4h5yb.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_sr030pc50.so:system/vendor/lib/libmmcamera_sr030pc50.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_fidelix_eeprom.so:system/vendor/lib/libmmcamera_fidelix_eeprom.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libTsAe.so:system/vendor/lib/libTsAe.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libTsAe.so:system/vendor/lib/E08QL_libTsAe.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libTsAf.so:system/vendor/lib/libTsAf.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libTsAf.so:system/vendor/lib/E08QL_libTsAf.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libTs_J_Accm.so:system/vendor/lib/libTs_J_Accm.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libTs_J_Accm.so:system/vendor/lib/E08QL_libTs_J_Accm.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libTs_J_Awb.so:system/vendor/lib/libTs_J_Awb.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/E08QL_libTs_J_Awb.so:system/vendor/lib/E08QL_libTs_J_Awb.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libAfSingle.so:system/vendor/lib/libAfSingle.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_s5k6a3yx_smart_stay.so:system/vendor/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_s5k6a3yx_vt_hd.so:system/vendor/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libchromatix_s5k6a3yx_vt.so:system/vendor/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_cac.so:system/vendor/lib/libmmcamera_cac.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libMMFW_scone_stub.so:system/vendor/lib/libMMFW_scone_stub.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/samsung/afyonltecan/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/afyonltecan/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libarcsoft_panorama_burstcapture.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_panorama_burstcapture.so

#RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdsucsd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsucsd.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libatparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libatparser.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libcordon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcordon.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libfactoryutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfactoryutil.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libomission_avoidance.so:$(TARGET_COPY_OUT_VENDOR)/lib/libomission_avoidance.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libcordon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcordon.so 

#RIL-G386WVLS1AQB1
PRODUCT_COPY_FILES += \
    vendor/samsung/afyonltecan/proprietary/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libgabi++.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgabi++.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libcorkscrew.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcorkscrew.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libgccdemangle.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgccdemangle.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdsnetutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsnetutils.so \

#QCOM RIL EXPERIMENT
PRODUCT_COPY_FILES += \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/rfs_access:$(TARGET_COPY_OUT_VENDOR)/bin/rfs_access \
    vendor/samsung/afyonltecan/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/samsung/afyonltecan/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/afyonltecan/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/samsung/afyonltecan/proprietary/vendor/etc/permissions/qcnvitems.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcnvitems.xml \
    vendor/samsung/afyonltecan/proprietary/vendor/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcrilhook.xml \
    vendor/samsung/afyonltecan/proprietary/vendor/framework/qcnvitems.jar:$(TARGET_COPY_OUT_VENDOR)/framework/qcnvitems.jar \
    vendor/samsung/afyonltecan/proprietary/vendor/framework/qcrilhook.jar:$(TARGET_COPY_OUT_VENDOR)/framework/qcrilhook.jar \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdataitems.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_csvt_srvc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csvt_srvc.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libril-qc-qmi-1_patched.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystem_health_mon.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libuicc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuicc.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libvss_common_idl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_common_idl.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libvss_common_iface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_common_iface.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libvss_nv_idl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_nv_idl.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libvss_nv_iface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_nv_iface.so \
    vendor/samsung/afyonltecan/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so

#Shims
PRODUCT_PACKAGES += \
    libshim_atomic \
    libshim_cutils \
    qcrilmsgtunnel \
    shutdownlistener \
    libaudiosystem_shim

